In [ ]:
# testing now 1

In [ ]:
import torch
from torch.autograd import Variable

# <font color='red'> input is scalar; output is scalar </font> 

### <font color='yellow'> Try - 1  

In [ ]:
x = Variable(torch.rand(1), requires_grad=True)
x

tensor([0.9743], requires_grad=True)

In [ ]:
y = 3*x**2

In [ ]:
y

tensor([2.8478], grad_fn=<MulBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad   # 6 * 0.9743

tensor([5.8458])

In [ ]:
6 * 0.9743  # 6 * x

5.8458000000000006

### <font color='yellow'> Try - 2 </font>

In [ ]:
x = Variable(torch.rand(1), requires_grad=True); x

tensor([0.7325], requires_grad=True)

In [ ]:
y = 3*x**2 ; y

tensor([1.6099], grad_fn=<MulBackward0>)

In [ ]:
torch.ones(1)

tensor([1.])

In [ ]:
y.backward(gradient=torch.ones(1))
x.grad

tensor([4.3953])

In [ ]:
0.7325 * 6

4.3950000000000005

### <font color='yellow'> Try - 3 </font>

In [ ]:
x = Variable(torch.rand(1), requires_grad=True); x

tensor([0.3478], requires_grad=True)

In [ ]:
y = 3*x**2
y.backward(gradient=100*torch.ones(1))
x.grad

tensor([208.6534])

In [ ]:
6 * 0.3478 * 100

208.68

# <font color='Red'> input is vector; output is scalar

### <font color='yellow'> Try - 1

In [ ]:
x = Variable(torch.rand(2, 1), requires_grad = True); x

tensor([[0.9769],
        [0.6559]], requires_grad=True)

In [ ]:
y = x[0]**3 + 2*x[1]**2

y.backward()


In [ ]:
x.grad

tensor([[2.8629],
        [2.6237]])

In [ ]:
# Grad: 
3*x[0]**2, 4*x[1]

(tensor([2.8629], grad_fn=<MulBackward0>),
 tensor([2.6237], grad_fn=<MulBackward0>))

### <font color='yellow'> Try - 2

In [ ]:
x = Variable(torch.rand(2, 1), requires_grad = True); x

tensor([[0.3901],
        [0.8963]], requires_grad=True)

In [ ]:
torch.ones(1)

tensor([1.])

In [ ]:
y = x[0]**3 + 2*x[1]**2

y.backward(gradient=torch.ones(1)) # Equiavalent of y.backward()

In [ ]:
x.grad

tensor([[0.4564],
        [3.5853]])

In [ ]:
3*x[0]**2, 4*x[1]

(tensor([0.4564], grad_fn=<MulBackward0>),
 tensor([3.5853], grad_fn=<MulBackward0>))

### <font color='yellow'> Try - 3

In [ ]:
x = Variable(torch.rand(2, 1), requires_grad = True); x

tensor([[0.5843],
        [0.0087]], requires_grad=True)

In [ ]:
y = x[0]**3 + 2*x[1]**2

y.backward(gradient=100*torch.ones(1))

In [ ]:
x.grad


tensor([[102.4362],
        [  3.4961]])

In [ ]:
100 * 3*x[0]**2, 100 * 4*x[1]

(tensor([102.4362], grad_fn=<MulBackward0>),
 tensor([3.4961], grad_fn=<MulBackward0>))

# <font color='red'> Input is scalar; output is vector

In [ ]:
x = Variable(torch.rand(1), requires_grad=True); x

tensor([0.7315], requires_grad=True)

In [ ]:
y = Variable(torch.zeros(2, 1), requires_grad=False)

In [ ]:
y

tensor([[0.],
        [0.]])

In [ ]:
y[0] = x**3
y[1] = 2*x**2
y

tensor([[0.3914],
        [1.0701]], grad_fn=<CopySlices>)

In [ ]:
y.size()

torch.Size([2, 1])

In [ ]:
y.backward(gradient=torch.ones(y.size()))

In [ ]:
x.grad

tensor([4.5310])

In [ ]:
3*x**2 + 4*x


tensor([4.5310], grad_fn=<AddBackward0>)

# <font color='red'> Input is vector; output is vector

### <font color='yellow'> Try - 1

In [ ]:
x = Variable(torch.rand(2, 1), requires_grad = True); x

tensor([[0.7756],
        [0.7654]], requires_grad=True)

In [ ]:
y = Variable(torch.zeros(3, 1), requires_grad=False)

In [ ]:
y

tensor([[0.],
        [0.],
        [0.]])

In [ ]:
y[0] = x[0]**2
y[1] = x[1]**3
y[2] = x[1]**4

In [ ]:
y.backward(gradient=torch.ones(y.size()))


In [ ]:
x.grad

tensor([[1.5512],
        [3.5507]])

In [ ]:
2*x[0], 3*x[1]**2, 4*x[1]**3


(tensor([1.5512], grad_fn=<MulBackward0>),
 tensor([1.7574], grad_fn=<MulBackward0>),
 tensor([1.7934], grad_fn=<MulBackward0>))

In [ ]:
2*x[0], (3*x[1]**2 + 4*x[1]**3)

(tensor([1.5512], grad_fn=<MulBackward0>),
 tensor([3.5507], grad_fn=<AddBackward0>))

### <font color='yellow'> Try - 2

In [ ]:
x = Variable(torch.rand(2, 1), requires_grad = True); x

tensor([[0.3400],
        [0.0747]], requires_grad=True)

In [ ]:
y = Variable(torch.zeros(3, 1), requires_grad=False)

In [ ]:
y

tensor([[0.],
        [0.],
        [0.]])

In [ ]:
y[0] = x[0]**2
y[1] = x[1]**3
y[2] = x[1]**4


In [ ]:
y.backward(gradient=100*torch.ones(y.size()))

In [ ]:
x.grad


tensor([[67.9920],
        [ 1.8424]])

In [ ]:
2*x[0], 3*x[1]**2, 4*x[1]**3

(tensor([0.6799], grad_fn=<MulBackward0>),
 tensor([0.0168], grad_fn=<MulBackward0>),
 tensor([0.0017], grad_fn=<MulBackward0>))

In [ ]:
2*x[0], 3*x[1]**2 + 4*x[1]**3

(tensor([0.6799], grad_fn=<MulBackward0>),
 tensor([0.0184], grad_fn=<AddBackward0>))